{% set goname = "github.com/jaegertracing/jaeger" %}
{% set version = "1.23.0" %}
{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/' + goname).replace("/", os.sep) %}

{% set goname_ui = "github.com/jaegertracing/jaeger-ui" %}
{% set version_ui = "1.12.0" %}
{% set pkg_src_ui = ('src/' + goname + '/jaeger-ui').replace("/", os.sep) %}

package:
  name: {{ name }}-build
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: 7b66b1525a35a35c088ef1117b344de88bf9a5c6500a3270b2dca197377f9f7a
    patches:
      - git.patch
  - folder: {{ pkg_src_ui }}
    url: https://{{ goname_ui }}/archive/v{{ version_ui }}.tar.gz
    sha256: 2b4f2fb35516360d0ad0e308365f351ae3cf4c20455f2e1dc72d3493baf476b1

build:
  number: 0
  skip: true  # [win]
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    # TODO: figure out how to make go-licenses work (many missing)
    # - go-licenses
    - make
    - nodejs >=12
    - yarn
  host:
    - go-dep

test:
  commands:
    - echo "tests in subpackages"

outputs:
  - name: {{ name }}
    requirements:
      run:
        - {{ pin_compatible(name ~ "-all-in-one") }}
        - {{ pin_compatible(name ~ "-agent") }}
        - {{ pin_compatible(name ~ "-collector") }}
        - {{ pin_compatible(name ~ "-ingester") }}
        - {{ pin_compatible(name ~ "-query") }}
        - {{ pin_compatible(name ~ "-example-hotrod") }}
        # jaeger-tracegen is in the standard build, but not the distribution

  - name: {{ name }}-agent
    script: copy_bin.sh
    test:
      commands:
        - {{ name }}-agent --help

  - name: {{ name }}-all-in-one
    script: copy_bin.sh
    test:
      commands:
        - {{ name }}-all-in-one --help

  - name: {{ name }}-collector
    script: copy_bin.sh
    test:
      commands:
        - {{ name }}-collector --help

  - name: {{ name }}-ingester
    script: copy_bin.sh
    test:
      commands:
        - {{ name }}-ingester --help

  - name: {{ name }}-query
    script: copy_bin.sh
    test:
      commands:
        - {{ name }}-query --help

  - name: {{ name }}-tracegen
    script: copy_bin.sh
    test:
      commands:
        - {{ name }}-tracegen --help

  - name: {{ name }}-example-hotrod
    script: copy_bin.sh
    test:
      commands:
        - example-hotrod --help

about:
  home: https://www.jaegertracing.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: CNCF Jaeger, a Distributed Tracing Platform

  description: |
    Jaeger, inspired by Dapper and OpenZipkin, is a distributed tracing system
    released as open source by Uber Technologies.
    It is used for monitoring and troubleshooting microservices-based
    distributed systems.
  doc_url: https://www.jaegertracing.io/docs
  dev_url: https://github.com/jaegertracing/jaeger

extra:
  recipe-maintainers:
    - saulshanabrook
    - goanpeca
    - bollwyvl
