{% set goname = "github.com/jaegertracing/jaeger" %}
{% set version = "1.18.1" %}
{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/' + goname).replace("/", os.sep) %}

{% set goname_ui = "github.com/jaegertracing/jaeger-ui" %}
{% set version_ui = "1.6.0" %}
{% set pkg_src_ui = ('src/' + goname + '/jaeger-ui').replace("/", os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: c88318011a397a004154d7d67d688d2ec93b9ded1ac76880e2eb1ba5a4e65b0d
    patches:
      - git.patch
  - folder: {{ pkg_src_ui }}
    url: https://{{ goname_ui }}/archive/v{{ version_ui }}.tar.gz
    sha256: 149530dd8fd2b2d03bcc9c9a594d1161f4641f0de12618ebda94d039407d8282

build:
  number: 0
  binary_relocation: false
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - make
  host:
    - go-dep
    - nodejs
    - yarn

test:
  commands:
    - jaeger-all-in-one --help  # [not win]
    - jaeger-all-in-one.exe --help  # [win]

about:
  home: https://www.jaegertracing.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: CNCF Jaeger, a Distributed Tracing Platform

  description: |
    Jaeger, inspired by Dapper and OpenZipkin, is a distributed tracing system released as open source by Uber Technologies.
    It is used for monitoring and troubleshooting microservices-based distributed systems.
  doc_url: https://www.jaegertracing.io/docs/{{ version }}/
  dev_url: https://github.com/jaegertracing/{{ name }}

extra:
  recipe-maintainers:
    - saulshanabrook
    - goanpeca
